config/routes.rb
Rails.application.routes.draw do
  get 'likes/add_favorite'

  get 'likes/destroy_favorite'

  get 'users/show'

  devise_for :users

  root 'home#index'

  resources :tests, only: [:index,:create]
  resources :top, only: [:index]
  resources :auto_matches, only: [:show]
  resources :users do
    resources :likes, only: [:create, :destroy]
  end

  post '/users/:user_id/likes/add', to: 'likes#delete_likes', as: :delete
  post '/users/:user_id/likes/delete', to: 'likes#add_likes', as: :add_likes
  

  devise_scope :user do
    delete 'users/logout', to: 'devise/sessions#destroy'
  end

  namespace :api do
    get '/maps/get_location', action: :get_location, controller: :maps
  end

  scope module: :users do
    resources :users, only: [] do
      resources :direct_messages, only: [:index, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direct_message.rb
class DirectMessage < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: :sender_id
  belongs_to :receiver, class_name: 'User', foreign_key: :receiver_id
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, counter_cache: :likes_count
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # TODO: mail認証をする時にconfirmable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  geocoded_by :location
  validates :nickname, presence: true
  validates :age, presence: true
  validates :location, presence: true
  validates :sexuality, presence: true
  after_validation :geocode
  has_many :direct_messages, foreign_key: :sender_id
  has_many :likes, dependent: :destroy
  enum sexuality: %w(lesbian gay bisexual mtof ftom etc)

  def like_user(user_id)
    !!Like.find_by(user_id: user_id)
  end

  class << self
    def get_recommended_users(user)
      near_users = User.where.not(id: user.id).near(user.location)
      near_users.order(likes_count: :desc).limit(3)
    end
  end
end

app/controllers/api/maps_controller.rb
class Api::MapsController < ApplicationController
  def get_location
    @user = current_user
    location = @user.present? ? Geocoder.coordinates(@user.location) : Geocoder.coordinates("Tokyo, Japan")
    render json: location, status: :ok
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def get_all_users
    users = current_user.present? ? User.where.not("id = ? AND location = ?", current_user.id, nil) : User.where.not(location: nil)
    users.to_json(only: [:id, :nickname, :latitude, :longitude])
    render json: users, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    # auto_matchが完成したら
    # auto_match_path
    # top_index_path
    if request.referer.include?('users/sign_in')
      top_index_path
    else
      '/auto_matches/show'
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :age, :location, :sexuality, :name, :icon_image, :description]) 
  end

end

app/controllers/auto_matches_controller.rb
class AutoMatchesController < PermissionController
  def show
    @user = current_user
    @target_user = User.order("likes_count desc").limit(1).where.not(id: current_user.id)[0]
  end
end

app/controllers/concerns/evaluation.rb
module Evaluation
  def self.evaluation(value)
    value >= 7
    if value >= 7
      return true
    end
    return false
  end

  # 今後の拡張次第では使用の可能性あり

  def self.verification(value)
    value.each do |key, val|
      if key.to_i == 65 && val <= 8
        return false
      elsif key.to_i == 67 && val <= 8
        return false
      elsif key.to_i >= 43 && val <= 2
        return false
      end
    end
    return true
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(user_id: current_user.id, target_id: params[:user_id])
    @likes = Like.where(target_id: params[:user_id])
    redirect_to request.referrer
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, target_id: params[:id])
    like.destroy
    @likes = Like.where(target_id: params[:user_id])
    redirect_to request.referrer
  end
end

app/controllers/permission_controller.rb
class PermissionController < ApplicationController
  before_action :authenticate_user!

  class NotPermissionError < StandardError; end

  rescue_from NotPermissionError do
    redirect_to root_path, alert: "You can't do it"
  end

  def confirm_user(resource)
    if resource.class.name == 'User'
      raise NotPermissionError if current_user != resource
    else
      raise NotPermissionError if current_user != resource.user
    end
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index; end
  def create
    value = params[:result]
    result = 0
    value.each do |key, val|
      result += val.to_i
    end
    if result >= 7
      return redirect_to '/users/sign_up'
    end
    redirect_to '/'
  end
end

app/controllers/top_controller.rb
class TopController < PermissionController
  def index
    @recommended_user = User.get_recommended_users(current_user)
  end
end

app/controllers/users/direct_messages_controller.rb
module Users
  class DirectMessagesController < ApplicationController
    before_action :set_context

    def index
      @message = DirectMessage.new
    end

    def create
      @message = current_user.direct_messages.new(create_params)
      if @message.save
        render json: @message.to_json
      else
        flash.now[:alert] = 'メッセージの送信に失敗しました。'
        render :index
      end
    end

    private

    def create_params
      params.require(:direct_message).permit(:text).merge(receiver_id: params[:user_id])
    end

    def set_context
      @partner = User.find(params[:user_id])
      @messages = DirectMessage
                    .where(sender_id: [current_user.id, @partner.id], receiver_id: [current_user.id, @partner.id])
                    .order(:created_at)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < PermissionController
  def show
    @user = User.find(params[:id])
    @likes = Like.where(target_id: params[:id])
    @likes_count = Like.where(target_id: params[:id]).count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auto_matching_helper.rb
module AutoMatchingHelper
end

app/helpers/lgbt_test_helper.rb
module LgbtTestHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auto_matches/show.html.slim
h1 初めてのマッチング

.row
  .col-md-6.col-md-offset-3
    p = "ようこそ！ #{@user.nickname}さん"
    - if !@target_user
      p マッチングに失敗しました
    - else
      / TODO: ユーザーの写真
      p = "#{@target_user.nickname}さんと話してみましょう！"
      p = link_to '話してみる', user_direct_messages_path(@target_user), class: 'btn btn-primary'

app/views/home/index.html.slim
= stylesheet_link_tag "https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
= javascript_include_tag "https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
= javascript_include_tag "root_mapping"

body.w3-light-gray
  .w3-container style="max-width:1600px;"
    .w3-center.w3-padding-24.w3-margin-10.w3-white
      h2 style=" font-family: 'ant-kaku';"
        | Diversity
      h2.w3-xxxlarge.w3-text-orange style=" font-family: 'ant-kaku';"
        b.w3-margin-28
        | 5分で見つかる
        br
        |近くの"ナカマ"
      h5 style=" font-family: 'ant-kaku';"
        | 10代のセクシャルマイノリティのための
        br
        | コミュニティサイト
      .w3-center.w3-padding-28.w3-white
        .panel-heading
          h2 style=" font-family: 'ant-kaku';"
            | WHAT'S DIVERSITY?
        .panel-body
          h4 style=" font-family: 'ant-kaku';"
            |「家族や友達に話せない本当の自分」
            br
            | 好きな相手や将来のことを先輩に気軽に話してみませんか？

.panel-group
  .panel.panel-primary style="margin: auto; padding: 10px;max-width: 100%; width: 80%; margin-top: 20px;"
    .panel-heading.w3-center 日本のナカマ
    .panel-body
      #map style="width: 100%; height: 450px; margin: auto; padding: 10px;"

app/views/likes/add_favorite.html.slim
h1 Likes#add_favorite
p Find me in app/views/likes/add_favorite.html.slim

app/views/likes/destroy_favorite.html.slim
h1 Likes#destroy_favorite
p Find me in app/views/likes/destroy_favorite.html.slim

app/views/top/index.html.slim
= stylesheet_link_tag "https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
= javascript_include_tag "https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
= javascript_include_tag "root_mapping"

.panel-group
  .panel.panel-primary style="margin: auto; padding: 10px;max-width: 90%; width: 100%; margin-top: 20px;"
    .panel-heading あなたの近くのナカマ
    .panel-body
      #map style="width: 100%; max-height: 80%;height: 450px; margin: auto; padding: 10px;"
  .panel.panel-default style="margin: auto; padding: 10px;width: 80%; margin-top: 20px;"
    .panel-heading おすすめのセンパイ
    .panel-body
      - if @recommended_user.present?
        table.table.table-striped
          thead
            tr
              td ニックネーム
              td ありがとうスコア
              td プロフィール
              td 話してみる
          - @recommended_user.each do |user|
            tbody
              tr
                td = user.nickname
                td = user.likes_count
                td = link_to 'Profile', user_path(user.id), class: "btn btn-primary btn-md"
                td = link_to 'Chat', user_direct_messages_path(user.id), class: "btn btn-info btn-md"

app/views/users/direct_messages/index.html.slim
header
  div.bg-primary
    nav
      ul.nav.nav-tabs
        li = link_to 'Top', top_index_path

.direct_message data-current=current_user.id
  .col-sm-3.col-sm-offset.frame
    .partner_info style="background-color: #FFADAD; border-radius: 15px; padding: 5px; margin: 5px;"
      p = "#{@partner.name}さんとチャットしてみましょう"
      p = "性志向: #{@partner.sexuality}"

    ul.messages_list
      - @messages.each do |message|
        - if message.sender_id == current_user.id
          li.my_each_message style="width: 100%;"
            .msj.macro
              .message_text.text.text-l
                = message.text
        - else
          li.partner_each_message style="width: 100%;"
            .msj-rta.macro
              .message_text.text.text-r
                p = message.text

    .msj-rta.macro style="margin:auto"
      .text.text-r style="background:whitesmoke !important"
        = form_for [@partner, @message], url: user_direct_messages_path do |f|
          .form-group
            = f.text_field :text, id: 'message_field', class: 'mytext form-control', placeholder: 'Type a messag'
          = f.submit '送信', class: 'btn btn-default'

app/views/users/show.html.slim
p
  .row
    .col-sm-3
      p style="margin: auto; padding: 10px; margin: 20px;"
        - if @user.icon_image.present?
          = image_tag @user.icon_image, size: "150x150"
        - else
          = image_tag 'human.jpeg', size: "150x150"
      p
        = @likes_count
        | 人にありがとうされています

    .col-sm-5
      table style="margin: 30px;"
        tr
          th 名前
          th
            h4
              b
                = @user.nickname
        tr
          th 年齢
          th
            h5
              = @user.age
        tr
          th 性志向
          th
            h6
              = @user.sexuality
        tr
          th 居住地
          th
            h6
              = @user.location
        tr
          th 自己紹介
          th
            h5
              |
              - if @user.description.blank?
                br
                | まだ自己紹介を登録していません
              - else
                = @user.description
    .col-sm-10 style="margin: 20px;"
      - if current_user.id != @user.id
        - if @user.like_user(current_user.id)
          = button_to user_like_path(@likes, target_id: @user.id), class: "btn btn-primary", method: :delete do
            span
              | ありがとうを取り消す
        - else
          = button_to user_likes_path(@user), class: "btn btn-primary" do
            span
              | ありがとう
        = link_to 'メッセージを送る', user_direct_messages_path(@user), class: "btn btn-primary"